complete -c bun -f -n __fish_use_subcommand -a add -d "Add a dependency to package.json"
complete -c bun -f -n __fish_use_subcommand -a audit -d "Check installed packages for vulnerabilities"
complete -c bun -f -n __fish_use_subcommand -a build -d "Transpile and bundle one or more files"
complete -c bun -f -n __fish_use_subcommand -a create -d "Create a new project from a template"
complete -c bun -f -n __fish_use_subcommand -a init -d "Initialize a Bun project in this directory"
complete -c bun -f -n __fish_use_subcommand -a install -d "Install dependencies from package.json"
complete -c bun -f -n __fish_use_subcommand -a link -d "Register or link a local npm package"
complete -c bun -f -n __fish_use_subcommand -a outdated -d "Display the latest versions of outdated dependencies"
complete -c bun -f -n __fish_use_subcommand -a pm -d "Additional package management utilities"
complete -c bun -f -n __fish_use_subcommand -a publish -d "Publish your package from local to npm"
complete -c bun -f -n __fish_use_subcommand -a remove -d "Remove a dependency from package.json"
complete -c bun -f -n __fish_use_subcommand -a run -d "Execute Run a package.json script or file"
complete -c bun -f -n __fish_use_subcommand -a unlink -d "Unregister a local npm package"
complete -c bun -f -n __fish_use_subcommand -a update -d "Update outdated dependencies"
complete -c bun -f -n __fish_use_subcommand -a upgrade -d "Upgrade to latest version of Bun"
complete -c bun -f -n __fish_use_subcommand -a x -d "Execute a package binary (CLI)"
