auto_sync = true
enter_accept = true
filter_mode = "global"
history_filter = [
  "^[[:alnum:]]+\\s*$",
  "^$",
  "^cd",
  "^code",
]
search_mode = "fulltext"
secrets_filter = true
show_help = false
show_tabs = false
style = "compact"
update_check = true

[stats]
ignored_commands = [
  "cd",
  "ls",
  "ll",
  "la",
  "gst",
]

[keys]
scroll_exits = false

[sync]
records = true
